### ISSUE TITLE
What is the speed during inference?

### ISSUE THREAD

**Issue by by2101** [athena-team/athena-decoder#5]
Hi, athena-team,

I wrote my own WFST based decoder in python. I found that it may iterate many arcs for a state. Becouse for loop is very slow in python, so the decoding speed is very slow. I also build LG graph. The inputs are 4233 characters, and the outputs are words.  I would like to know is it fast enough for your decoder? Thank you!

Best,
by2101

**Comment by godjealous** [comment]
Certainly, the python version decoder is slower than C++ version decoder but not that much.

For example, for LG graph there are fewer successor nodes and emitting arcs for every states than HCLG graph.

You could try to reduce beam size and max active tokens size to speed up. 

honestly， the purpose of this python version decoder is verifing experiment results quickly. We do not pay much attention to the speed optimization。

It is recommended to use C++ version decoder in  production environment or other environment that have requirement for speed.

The C++ version of the decoder will be open sourced in the same project soon.

Thanks.

**Comment by by2101** [comment]
The information is very useful. Thank you!
